version: '3.8'

services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4000:4000"
    env_file:
      - ./frontend/.env
    command: sh -c "chmod +x /app/start-frontend.sh && /app/start-frontend.sh"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static  # Mount the static directory
      - model-cache:/root/.cache/huggingface  # Add this line
    ports:
      - "4001:4001"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
      - image-processing-service

  image-processing-service:
    build:
      context: ./image-processing-service
      dockerfile: Dockerfile
    volumes:
      - ./image-processing-service/src:/app/src
    ports:
      - "4002:4002"
    env_file:
      - ./image-processing-service/.env

  mongo:
    container_name: climbing-mongo
    image: mongo:latest
    user: "999:999"
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: >
      --wiredTigerCacheSizeGB 1
      --setParameter diagnosticDataCollectionEnabled=false
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  mongo-data:
  model-cache:  # Add this volume