version: '3.8'

services:
  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_API_URL=http://localhost:4001
    command: sh -c "chmod +x /app/start-frontend.sh && /app/start-frontend.sh"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static  # Mount the static directory
      - model-cache:/root/.cache/huggingface  # Add this line
    ports:
      - "4001:4001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DB=climbing
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - TRANSFORMERS_CACHE=/root/.cache/huggingface  # Add this line
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    user: "999:999"
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    command: >
      --wiredTigerCacheSizeGB 1
      --setParameter diagnosticDataCollectionEnabled=false
    deploy:
      resources:
        limits:
          memory: 2G

volumes:
  mongo-data:
  model-cache:  # Add this volume