version: '3.8'

services:
  bb-frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./bb-frontend:/app
    ports:
      - "4000:4000"
    env_file:
      - ./frontend/.env
    command: sh -c "chmod +x /app/start-frontend.sh && /app/start-frontend.sh"
    depends_on:
      - bb-backend

  bb-backend:
    build:
      context: ./bb-backend
      dockerfile: Dockerfile
    volumes:
      - ./bb-backend:/app
      - ./bb-backend/static:/app/static  # Mount the static directory
      - model-cache:/root/.cache/huggingface  # Add this line
    ports:
      - "4001:4001"
    env_file:
      - ./bb-backend/.env
    depends_on:
      - bb-cv

  bb-cv:
    build:
      context: ./bb-cv
      dockerfile: Dockerfile
    volumes:
      - ./bb-cv/src:/app/src
    ports:
      - "4002:4002"
    env_file:
      - ./bb-cv/.env

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  # betaboard-camera:
  #   build:
  #     context: ./betaboard-camera
  #     dockerfile: Dockerfile.amd64
  #   volumes:
  #     - ./betaboard-camera:/app
  #     - ./betaboard-camera/static/videos:/opt/betaboard-camera/videos
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - ./betaboard-camera/.env

volumes:
  model-cache:  # Add this volume