"""Add sensor reading frame index

Revision ID: 46b78c4ee6dc
Revises: d0818eee6354
Create Date: 2024-10-30 20:54:31.819704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b78c4ee6dc'
down_revision: Union[str, None] = 'd0818eee6354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor_readings', sa.Column('frame_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor_readings', 'frame_index')
    # ### end Alembic commands ###
