"""add video key to recording

Revision ID: 307af79213b0
Revises: 46b78c4ee6dc
Create Date: 2024-11-06 23:01:57.772578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '307af79213b0'
down_revision: Union[str, None] = '46b78c4ee6dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recordings', sa.Column('video_s3_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recordings', 'video_s3_key')
    # ### end Alembic commands ###
